### ISSUE TITLE
POST https://sdk.supportkit.io/api/appusers/undefined 404 (Not Found)

### ISSUE THREAD

**Issue by appjitsu** [smooch/smooch-js#117]
I am using the web version of the api in a meteor project. It is loaded in via a script tag in the header.

    <script src="https://cdn.supportkit.io/supportkit.min.js"></script>

Then later on in the client side code:

    if (Meteor.isCordova) {
      Meteor.startup(function() {

        SupportKit.on('ready', function() {
          console.log('supportkit init complete!');
        });

        SupportKit.init({
          "appToken": "***********"
        });

      });
    }

Then I get an error:

    POST https://sdk.supportkit.io/api/appusers/undefined 404 (Not Found) supportkit.min.js:14

This only happens on android. iOS works fine.

@cosio55

**Comment by appjitsu** [comment]
Is there a way to make this work via cordova?

**Comment by lemieux** [comment]
Hey @appjitsu,

did you try this https://github.com/supportkit/supportkit-cordova ?

**Comment by appjitsu** [comment]
Yes, but I need more documentation or an example of how to get it to work.

**Comment by lemieux** [comment]
Ok, I'll check that out with the team tomorrow then.

**Comment by edchan77** [comment]
hey @appjitsu there's an Android cordova code example in the repo, was that of any help? https://github.com/supportkit/supportkit-cordova/tree/master/example/android

**Comment by appjitsu** [comment]
I didn't see this example beforehand. I had code almost just like this, but
it didn't work for some reason. I will take a close look at this and try
again.

Thanks!

**Comment by lemieux** [comment]
I'll close this one since it seems to be more related to Cordova.
