### ISSUE TITLE
require('url-join') is wrong in 2.0.0

### ISSUE THREAD

**Issue by palmerabollo** [smooch/smooch-js#123]
In the published smooch 2.0.0 there is a `require('url-join')` ([see code](https://github.com/smooch/smooch-js/blob/master/src/js/main.js#L8)) instead of `require('urljoin')` that breaks browserify process:

> Error: Cannot find module 'url-join' from '/Users/test/node_modules/smooch/src/js'

It is apparently fixed in the integration branch. Would it be possible to release a 2.0.1 version that fixes this issue? Otherwise the installation steps described in [the docs](http://docs.smooch.io/javascript/#npm-and-browserify) are broken.

**Comment by lemieux** [comment]
Hey @palmerabollo, we will release a fix for this shortly. It was fixed in https://github.com/smooch/smooch-js/commit/dfab1a2266b9ba7fb4822964de08ce418c40d43f but we didn't deployed it.. sorry :(

We'll keep you updated!

**Comment by lemieux** [comment]
We just released 2.0.1 with that fix.

**Comment by palmerabollo** [comment]
Thanks for the quick fix.
