### ISSUE TITLE
Undesired behavior: Smooch.updateUser opens the chat window

### ISSUE THREAD

**Issue by pronav** [smooch/smooch-js#140]
Invoking `Smooch.updateUser` makes chat window open up as soon as promise is resolved. Though chat window doesn't seem to be "fully" in open state, as header needs to be clicked twice to make it close itself.

To produce, go to https://dashboard.razorpay.com and run `Smooch.updateUser({givenName: 'Hello World'})` in console.

I've checked with my custom code removed, the bug is still there. Things work normally with old supportkit.min.js, so this should be recent.

**Comment by captn3m0** [comment]
I'll ask on supportkit chat, but can you file an issue on smooch.js as well?

**Comment by lemieux** [comment]
Thanks for reporting this, I'll have a look at it today.

**Comment by lemieux** [comment]
@pronav I found the problem and I'll deploy a fix for it today. I'm surprised the behavior wasn't present with the supportkit.min.js package, that piece of code is there for a while now.

Anyways.. fixed :)

**Comment by lemieux** [comment]
@pronav fix deployed! I tested on your app and it seems to be good now.

**Comment by pronav** [comment]
Thanks for the super-fast fix! Didn't notice the bug on https://razorpay.com, which has old package. It probably happens only with first time user/incognito.
