### ISSUE TITLE
Including smooch via NPM fails due to missing /dist directory

### ISSUE THREAD

**Issue by ElijahGlover** [smooch/smooch-js#163]
Hi Marc-Antoine Lemieux,

I'm trying to include smooch using browserify. I'm getting the following when executing task:

```
Running "browserify:vendor" (browserify) task
>> Error: Cannot find module 'smooch' from '/vagrant/sails/portal/assets/js'
Warning: Error running grunt-browserify. Use --force to continue.
```

I've taken latest from NPM (2.1.1), packages.config defines main as `dist/smooch.js` which doesn't exist.

**Comment by lemieux** [comment]
Hey @ElijahGlover, thanks for the report. I'll look into it first thing tomorrow morning.

**Comment by lemieux** [comment]
@ElijahGlover we just release 2.1.2 on npm. It should make it usable now.

**Comment by ElijahGlover** [comment]
Thanks Marc-Antoine
