### ISSUE TITLE
File size?

### ISSUE THREAD

**Issue by reiberdatschi23** [smooch/smooch-js#168]
Hello,

We're using smooch for the web (this lib) but its overlay big for such a simple library. Your minified version turns out to be 127KB which might be the reasoning that it takes quite some time until the widget is really available / loaded, any idea?

**Comment by lemieux** [comment]
Hey @reiberdatschi23,

are you referring to the time it takes to be able to do `Smooch.init` or the time it takes before it actually renders?

**Comment by reiberdatschi23** [comment]
Well I might have mixed up things here. The first big issue is it takes due the file size quite some time to load to be able to call Smooch.init. The other issue however is that it takes 15-30 secs for the widgets to appear.

**Comment by lemieux** [comment]
I assume you are using the CDN version? Is your widget live somewhere? 15-30 secs is not a normal behavior... I'd like to take a look at it if possible.

**Comment by alavers** [comment]
@reiberdatschi23 is your page hosted somewhere we can see? If not, it might be worth analyzing your page load sequence using a tool like chrome dev tools:

https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en

**Comment by alavers** [comment]
Closing since the issue appears to be unrelated to the widget file size.
