### ISSUE TITLE
Observables for open/close?

### ISSUE THREAD

**Issue by mtwilliams** [smooch/smooch-js#180]
In the process of tying Smooch to a different button (floating, looks like Intercom), I had to use nasty hacks to determine if the chat widget was open (to hide the button). Being able to observe open/close events (especially started and completed variants) would've helped immensely.

**Comment by lemieux** [comment]
hey @mtwilliams, we'll make some improvements to the widget in the coming weeks and some of these improvements include adding more hooks for these kind of events. 

Do you think of anything else we should improve in order to make it easier to customize the widget experience?

**Comment by RobAzvd** [comment]
+1 on the Open/Closed state

**Comment by mtwilliams** [comment]
Woo!

@lemieux, the ability to _embed chat_ would be great.

**Comment by lemieux** [comment]
Good :) it's also in the planned improvements and I'm starting to work on
it next week.

**Comment by lemieux** [comment]
@mtwilliams ability to embed chat is getting deployed as we speak :) Events for open/close will follow probably tomorrow

**Comment by mtwilliams** [comment]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 

gonna tell all my friends that smooch is the :key:

@lemieux

**Comment by lemieux** [comment]
:) we should roll this out tomorrow

**Comment by lemieux** [comment]
@mtwilliams @RobAzvd events for open/close are deploying right now (version 2.1.9) and should be available on npm and cdn in a couple of minutes

**Comment by mtwilliams** [comment]
:heart:

**Comment by RobAzvd** [comment]
@lemieux Awesome, putting it in production now.
Thanks!
