### ISSUE TITLE
Error in updateUser() after login()

### ISSUE THREAD

**Issue by C00per** [smooch/smooch-js#192]
Hi!
I'm trying to execute 
```javascript
Smooch.login($scope.user.userID);                               
Smooch.updateUser({
	givenName: $scope.user.firstName,
	surname: $scope.user.lastName,
	email: $scope.user.email,
});
```
And get  the error below for Smooch.updateUser()

`Error: Must provide a JWT or a app token
    at n (smooch.js:25)
    at new f (smooch.js:25)
    at o (smooch.js:25)
    at o (smooch.js:26)
    at i (smooch.js:26)
    at e.t.Smooch.e.updateUser (smooch.js:7)`

I'm using version v2.1.9. 
Could someone please help?

**Comment by lemieux** [comment]
Hi @C00per did you call `Smooch.init` before calling `Smooch.login`? `init` must be the first thing done when using the widget. Internally, it's setting the appToken and/or jwt then calls `login`.

Actually, `init` is doing login + updateUser at the same time so you could probably use this : 
```
Smooch.init({
   appToken: '<your-app-token>',
   userId: $scope.user.userID,
   givenName: $scope.user.firstName,
    surname: $scope.user.lastName,
    email: $scope.user.email
})
```

**Comment by C00per** [comment]
Hi, @lemieux.
Yes, I call `Smooch.init` before calling `Smooch.login`. Actually `Smooch.login` and `Smooch.update` works well when I call them separately. But there is an error when I call them together, one by one.

I can replace both these calls with one `Smooch.init` called the second time and it works without error.  

Also, I tried to execute:
```javascript
Smooch.init //-->second time
Smooch.login
Smooch.update
```
And I get the same error on `Smooch.update`.

**Comment by lemieux** [comment]
Have you tried doing 
```
Smooch.login(...).then(function(){
    return Smooch.updateUser(...)
});
```

might be a concurrency problem where login didn't finish when you call updateUser

**Comment by C00per** [comment]
Yes! There was a concurrency problem. I got it when tried to execute `Smooch.updateUser` after a timeout and it worked just fine. I'll call `Smooch.updateUser` after promise resolving as you suggested.

Thank you!

**Comment by lemieux** [comment]
:+1:
