### ISSUE TITLE
getConversation method reset the appUser and return 0 unread message all the time

### ISSUE THREAD

**Issue by romain-web** [smooch/smooch-js#199]
Hy,
I have integrates smooch on our webapp, it's really cool! but i'm trying to open by default the tchat after the first load of the application if we have unread messages.

```
Smooch.init({
  appToken: 'xyz'
});

Smooch.on('ready', function () {
  Smooch.getConversation().then(function (conversation) {
    if (conversation.unreadCount > 0) {
      Smooch.open();
    }
  });
});
```

it's look like really simply, but if we run this we get errors when we sending messages.

<img width="635" alt="capture d ecran 2016-03-16 a 19 47 41" src="https://cloud.githubusercontent.com/assets/823314/13824890/40fa627a-ebb0-11e5-90a5-46b5770a4f1f.png">

so... ok I don't know why a getConversation reset the userApp settings but I tried to fix this by add

```
Smooch.on('ready', function () {
  
  [...]

  Smooch.updateUser({ [...] });
});
```

But at this time `unreadCount` was always set at `0`

Thanks in advance for your response 🦄

**Comment by Mario54** [comment]
Sorry about that. Looks like there was indeed a bug in `Smooch.getConversation()` which was overwriting the user. This will be fixed by #202.
