### ISSUE TITLE
Calling Smooch.destroy before Smooch.init throws ambiguous error

### ISSUE THREAD

**Issue by milesmatthias** [smooch/smooch-js#238]
When I call `Smooch.destroy` after the component is initialized, I see this error repeated every couple of seconds in the console:

`Uncaught Error: Must provide a JWT or a app token (auth.js:29)`

Anything I'm doing wrong here?

**Comment by lemieux** [comment]
Hey @milesmatthias , can you provide the complete call stack?

**Comment by milesmatthias** [comment]
```js
auth.js:29 Uncaught Error: Must provide a JWT or a app tokenn @ auth.js:29
f @ smooch.js:46
o @ core.js:10
c @ conversation-service.js:119
(anonymous function) @ faye.js:39
t.emit @ faye-browser.js:236
Faye.Dispatcher.Faye.Class.handleResponse @faye-browser.js:1587
Faye.Transport.Faye.extend.Faye.Class._receive @ faye-browser.js:1743
e.onmessage @ faye-browser.js:2442
```

**Comment by lemieux** [comment]
Thanks, seems like a bug on our side. Faye is probably not getting cleaned up properly on destroy. We'll investigate!

**Comment by Mario54** [comment]
Hey @milesmatthias, I tried for a bit, but I'm not able to reproduce the bug 😞 

Could you provide a code sample that reproduces it? It would point me in the right direction 🙂

**Comment by milesmatthias** [comment]
I'm afraid that I can't provide much here since I'm just calling `Smooch.destroy`.

```js
  if ('Smooch' in window) {
    try{
      Smooch.destroy(); 
    } catch(e) {};
  }
```

**Comment by Mario54** [comment]
I still can't reproduce. Are you calling `Smooch.init` beforehand, or are you directly calling `Smooch.destroy()` before calling `init`?

**Comment by milesmatthias** [comment]
The order may have something to do with it. Here's a screenshot of me in the console on our website doing destroy definitely after init (works) and then trying to call init and destroy again (errors): https://s3.amazonaws.com/screenshots.equityeats.com/pmUO4.png

**Comment by Mario54** [comment]
Just making sure, you are aware that when calling `Smooch.destroy` it will clear all state passed in to `Smooch.init` previously, so you need to send in either a jwt or an appToken to `init` every time you call it.

However, it looks like we are indeed not checking if `init` was called correctly before executing the `destroy` logic. We will fix that. 

Is that what you are concerned about?

**Comment by milesmatthias** [comment]
It does look like that's the error. A more descriptive error of the situation would definitely be helpful, thanks!
