### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by timneutkens** [smooch/smooch-js#252]
First of all... thanks for the awesome messaging / chat platform, Slack integration is great!
I'm working on a dutch website that has to have an all dutch chat widget. Taken from the docs tweaking / translating text strings is already possible:
```Javascript
Smooch.init({
        appToken: 'apitoken',
        customText: {
            headerText: 'How can we help?',
            inputPlaceholder: 'Type a message...',
            sendButtonText: 'Send',
            introText: 'This is the beginning of your conversation.<br/> Ask us anything!',
            settingsText: 'You can leave us your email so that we can get back to you this way.',
            settingsReadOnlyText: 'We\'ll get back to you at this email address if we missed you.',
            settingsInputPlaceholder: 'Your email address',
            settingsSaveButtonText: 'Save',
            settingsHeaderText: 'Email Settings',
            settingsNotificationText: 'In case we\'re slow to respond you can <a href data-ui-settings-link>leave us your email</a>.',
            actionPaymentError: 'An error occurred while processing the card. <br> Please try again or use a different card.',
            actionPaymentCompleted: 'Payment Completed',
            messageError: 'An error occured while sending your message. Please try again.',
            invalidFileError: 'Sorry, but only images are supported currently. Please choose a file with a supported extension (jpg, jpeg, png, gif, or bmp).',
            messageIndicatorTitleSingular: '({count}) New message',
            messageIndicatorTitlePlural: '({count}) New messages'
        }
    });
```

Which got me thinking.. why not create a small script that exports the right translations based on a country code. Something like:
```Javascript
Smooch.init({
    appToken: 'apitoken',
    customText: SmoochLanguages.get('nl-NL') // for dutch
});
```

Just wanted to check if this hasn't been created already. I would be happy to create a package that does the behaviour described ( dutch translations included ;-) ). Would love to hear your thoughts on the subject.

**Comment by lemieux** [comment]
Hey @timneutkens , funny you ask, we just talk about this today!

I can tell you that official support for multi-language is coming, but I don't have a timeframe for it yet.

However, feel free to build and publish such package in the meantime. This could really be useful for a lot of people and definitely be useful when we will add multi-language.

**Comment by williamsjj** [comment]
What candidates do you guys like for JS i18n/l10n?

**Comment by lemieux** [comment]
The current options are either i18next (http://i18next.com/) or formatJS (http://formatjs.io/). I'm leaning toward formatJS a lot because it can leverage the native Intl API (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Intl) from the browser, but nothing is set in stone at this point.

**Comment by timneutkens** [comment]
Will try to create a package tomorrow leveraging formatJS.

**Comment by timneutkens** [comment]
I went with the simple solution. It's available here https://github.com/timneutkens/smooch-languages

**Comment by lemieux** [comment]
Cool stuff :) 

I'll close this issue since there's nothing to do in this repo.
