### ISSUE TITLE
NPM doesn't install assets referenced in lib/constants

### ISSUE THREAD

**Issue by vicrep** [smooch/smooch-js#286]
In the latest release(s) (smooch@3.0.x), installing the library through npm only pulls the `lib` directory, but fails to pull the assets and images directories. This causes the following kind of errors on build (using gulp + browserify):

```
Error: Cannot find module '../../images/telegram_large_2x.png' from '<your/node/project>/node_modules/smooch/lib/constants'
```

Please let me know if you would like any additional information. Cheers

**Comment by lemieux** [comment]
Hey @vicrep ! Really sorry about that! Seems like I forgot to update the deploy script when I did some cleanup in that file.

#287 should fix that and I'll most likely will deploy that really soon.

**Comment by lemieux** [comment]
We just release v3.0.3 which should solve this problem! 

Again, sorry about that!

**Comment by vicrep** [comment]
Thank for the quick patch-up @lemieux ! Cheers
