### ISSUE TITLE
Events create errors

### ISSUE THREAD

**Issue by aessig** [smooch/smooch-js#301]
Hi, I'm using smooch in a meteor app, and I tried to include the package using NPM but it crashed, due to missing dependency. So I included the min.js file directly in the app, but when an event `widget.closed` is called I have this error 
`Refused to evaluate script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' `
And I don't think it would be a good idea to set up security to let evaluate inline script. Maybe I'm wrong. 
Do you have any idea, how I can solve that issue ? Cheers

**Comment by lemieux** [comment]
Hey! which version of npm are you using? smooch-js has peer dependencies and npm3 isn't installing them automatically like npm2 was. I need to update the docs about that. 

Can you try installing `babel-polyfill@6.9`, `babel-runtime@6.9`, `react@15`, and `react-dom@15` and see if it works with npm?

**Comment by aessig** [comment]
Thanks for your reply. Yes, I'm using npm3 and meteor. I just tried that and I didn't have any more errors from npm but I hit another issue. I have this error on the console now. 
` Uncaught Error: process.binding is not supported ` with the origin from `smooch.js:52` , `meteorInstall.node_modules.smooch.lib.smooch.js`, But I think it might be a problem coming from integration with meteor. Any help will be much appreciate. Cheers :)

**Comment by lemieux** [comment]
I'll close this issue since it seems to be related to meteor. Unfortunately, I don't know how meteor works to be able to help. Sorry!
