### ISSUE TITLE
Getting an error on Smooch.destroy function call

### ISSUE THREAD

**Issue by sadler42** [smooch/smooch-js#318]
Hi,

I have noticed an error in the console when calling the destroy function to remove the Smooch chat widget.
See https://fiddle.jshell.net/htzgjg84/

Does anyone have an idea of what could be the cause ?

Thanks.

**Comment by lemieux** [comment]
Hey @sadler42,

thanks for reporting this, I was able to reproduce the problem in development. We'll issue a fix today :)

Sorry about that!

**Comment by lemieux** [comment]
Hi, we just released a new version with the fix for the error thrown. It should be available automatically through the CDN and npm/bower.
