### ISSUE TITLE
Ionic 2 modal dialog not opening

### ISSUE THREAD

**Issue by marcelgoya** [smooch/smooch-js#334]
The JS SDK seems to prevent Ionic 2 Beta 10 from opening modal dialogs. Do you haven any idea what could cause this problem?

**Comment by lemieux** [comment]
It's really hard to tell without more information. Do you have any stack traces or a sample project that reproduces the problem?

**Comment by marcelgoya** [comment]
Sure, I'm going to create a sample code pen

**Comment by marcelgoya** [comment]
Alright, I don't know what it was but the problem seems to disappear when I'm loading the smoochjs file before the app bundle. So problem solved :)
