### ISSUE TITLE
Parsing package.json in smooch-core

### ISSUE THREAD

**Issue by varunarora** [smooch/smooch-js#350]
Hi guys,
I can't seem to resolve this error through Webpack (managed to resolve the `load-image` and `imports` ones):

`ERROR in ./~/smooch-core/package.json
Module parse failed: /home/xxxx/Code/xxxx/node_modules/smooch-core/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       "smooch-core@1.4.0",
 @ ./~/smooch-core/lib/smooch.js 14:15-41
`

Help?

**Comment by lemieux** [comment]
Hey, can you try adding something like this https://github.com/smooch/smooch-js/blob/integration/make-webpack-config.js#L35 (json loader for json files) to your webpack config? I realize this might not be ideal and we should fix smooch-core to prevent this from happening.

**Comment by varunarora** [comment]
Thanks @lemieux, that worked for now, but yeah, not ideal.

Thanks for the amazing work on making this available through npm.
