### ISSUE TITLE
emailCaptureEnabled Not Showing

### ISSUE THREAD

**Issue by bmpieretti** [smooch/smooch-js#373]
Hey Smooch Team!

I've tried integrating emailCaptureEnabled into a smooch widget, but it refuses to show up at all. I set 
`emailCaptureEnabled = true` in the config options, and no errors are thrown. Is this possibly broken in the latest release, or can someone help me out if I'm missing something?

**Comment by jpjoyal** [comment]
hi @bmpieretti 

`emailCaptureEnabled` only works if you don't have any other channels enabled. Did you enabled other messaging channels for the app you use ?

**Comment by bmpieretti** [comment]
Of course, but isn't the main draw of smooch the easy integration with other channels? That's what drew us at least, so why would the email capture be limited if there are other channels?

**Comment by jpjoyal** [comment]
`emailCaptureEnabled` predates our support for multi channels. If you use multi channels you can enable the Email Messaging integration to offer email as a channel to your users. It won't "capture" email addresses just yet but its coming :)

**Comment by jpjoyal** [comment]
I made this clearer in https://github.com/smooch/smooch-js/pull/376
