### ISSUE TITLE
Webpack + require('../constants/assets') => empty

### ISSUE THREAD

**Issue by cdupoiron** [smooch/smooch-js#397]
Hello,

I try to use smooch@3.4.1 with npm + webpack. (webpack bundle is valid.)

But, in my browser, in channels.js:43, this error happens: Cannot read property 'messenger' of undefined . 

require('../constants/assets') at line 22 return an empty object.

What can i do to resolve it? 

Thx

**Comment by lemieux** [comment]
Hey there, I think I found the problem and I'll release a fix in the next hour. I'll keep you posted.

**Comment by lemieux** [comment]
smooch@3.4.2 should be out on npm in a couple of minutes. That should fix the problem.

Sorry about that!
