### ISSUE TITLE
Webpack errors when installing with npm

### ISSUE THREAD

**Issue by freezy** [smooch/smooch-js#403]
I'm integrating Smooch with an Angular 2 app. So basically I ran `npm install smooch --save` and retrieved the instance by loading it like described in the doc: `Smooch = require('smooch')`.

However, when running the app, I'm getting a ton of errors. Here's an excerpt:

```
  [889] ./~/smooch-core/lib/utils/auth.js 720 bytes {1} [built]
  [890] ./~/smooch/lib/components/action.js 7.93 kB {1} [built] [5 errors]
  [891] ./~/smooch/lib/components/alternate-channels.js 2.28 kB {1} [built] [4 errors]
  [892] ./~/smooch/lib/components/channels/channel-page.js 3.75 kB {1} [built] [4 errors]
  [893] ./~/smooch/lib/components/channels/channel.js 4.1 kB {1} [built] [5 errors]
  [894] ./~/smooch/lib/components/channels/email-channel-content.js 1.81 kB {1} [built] [4 errors]
  [895] ./~/smooch/lib/components/channels/line-channel-content.js 1.36 kB {1} [built] [4 errors]
  [896] ./~/smooch/lib/components/channels/messenger-channel-content.js 3.1 kB {1} [built] [4 errors]
```
And below:

```
ERROR in ./~/smooch/lib/smooch.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/promise' in C:\dev\website\node_modules\smooch\lib
 @ ./~/smooch/lib/smooch.js 6:15-55

ERROR in ./~/smooch/lib/smooch.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\dev\website\node_modules\smooch\lib
 @ ./~/smooch/lib/smooch.js 10:16-56

ERROR in ./~/smooch/lib/smooch.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\dev\website\node_modules\smooch\lib
 @ ./~/smooch/lib/smooch.js 14:23-70

ERROR in ./~/smooch/lib/smooch.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/typeof' in C:\dev\website\node_modules\smooch\lib
 @ ./~/smooch/lib/smooch.js 18:15-54
```

and so on. Looking at your `package.json`, those seem to be all dev dependencies and are therefore not installed when installing through npm.

You can reproduce this quite easily by just cloning [angular/angular2-seed](https://github.com/angular/angular2-seed) running `npm install smooch` and requiring Smooch somewhere in the app, e.g. `app.ts`.

Any advice? I can try to manually install those deps, but I'm pretty sure that's not how this is supposed to work...

**Comment by lemieux** [comment]
Hey @freezy, `smooch` has a couple of peer dependencies that need to be installed too https://github.com/smooch/smooch-js/blob/integration/package.json#L146. My guess is that you're using npm3 and doesn't install them automatically like npm2 was.

**Comment by freezy** [comment]
When manually running `npm install` in the `node_modules/smooch` folder these error messages go away.

Anything you're planning to solve this?

I'm however running into another problem, but I'll open a new issue for it because I don't think it's related.

**Comment by lemieux** [comment]
Running `npm install` in `node_modules/smooch` will install dev dependencies which covers the peer dependencies, which is not recommended. Peer dependencies should be installed on your side instead. We had to do that because many of users already have `react` and `babel` in their dependencies and we had the avoid version clashing/duplication of dependencies.

There's nothing really to be fixed because that's how peer dependencies work. However, we will update the documentation to make it clearer that it's necessary.
