### ISSUE TITLE
Typings support

### ISSUE THREAD

**Issue by thielCole** [smooch/smooch-js#416]
I would like to include smooch in an Angular 2 / Ionic 2 project that I am building. To be able to import the library like I would underscore or lodash, It is necessary for typings to be included. 

Example:

    import _ from 'lodash';
    import Smooch from 'smooch';

    @Component({
      templateUrl: 'settings.page.html'
    })
    export class SmoochPage { }

Is their any plan on supporting typescript definition files?

**Comment by sportebois** [comment]
Hello

Types definition is not currently planned. Therefore the Typescript compiler will complain about `import` statement.  
But you should still be able to use a classic `require('Smooch')` and use it. 
Please keep in mind we're not using Ionic2 and have limited knowledge about it, so the following answer is more generic about how to use Smooch in a Typescript project.

For usual use-cases, a classic `const Smooch = require('smooch');`  let you use Smooch in Typescript code and you're fine.
After having a quick glimpse at Ionic2 it looks like the way the libs are loaded is more specific, and you might have to do it in two steps:
- make your ts happy with an explicit any declaration: rather than importing the lib, just declare it with `declare const Smooch: any;`
- copy the Smooch lib (either `smooch.min.js` file from the cdn or the Smooch js you installed in node_modules with npm) into your project `www` folder (or any subfolder you prefer)
- then load this Smooch js lib by adding a script tag in the `www/index.html`, like  `<script src="smooch.js"></script>` (if you place it directly in www)

Hope this helps,

**Comment by thielCole** [comment]
Hey @sportebois , so if anyone else is looking at this for ionic2 configuration, I solved the problem in a different way. 

First, because there was alot of overlap (particularly with promises) between zone.js and smooch, I imported the smooch.min.js tag as the last script tag in my index.html
```
<body>
  <!-- Ionic's root component and where the app will load -->
  <ion-app></ion-app>
  <!-- cordova.js required for cordova apps -->
  <!-- <script src="cordova.js"></script> -->
  <!-- Polyfill for intl, this should be included in future ionic releases -->
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script> 
  <!-- The polyfills js is generated during the build process -->
  <script src="build/polyfills.js"></script>
  <!-- The bundle js is generated during the build process -->
  <script src="build/main.js"></script>
  <script src="assets/smooch.min.js"></script>
</body>
```

Then I initialized it in my app.component.ts, because thats also where I validate login. That way I can add user information. I use firebase as my backend implementation here.

```
declare var Smooch: any;

... 

  ngAfterViewInit() {
    this.listenToLoginEvents();
    // this.listenForUpdates();
  }

  listenToLoginEvents() {

    this.af.auth.subscribe( (user) => {
      if (user) {
        // User is signed in.
        this.rootPage = TabsPage;
        // Initialize Smooch
        Smooch.init({
          'appToken':'an4tq3kng5aw0xknv6wvhedlg',
          embedded: true,
          userId: user.auth.uid,
          givenName: user.auth.displayName,
          email: user.auth.email
        });
      } else {
        this.rootPage = LoginPage;
      }
    });
   }
```

And then in the page that I actually want to embed the conversation, I use this component.

```
import { Component, AfterViewInit } from '@angular/core';
import { NavController } from 'ionic-angular';

declare var Smooch: any;

@Component({
  templateUrl: 'smooch.comp.html'
})
export class SmoochComponent implements AfterViewInit {

  constructor(public nav: NavController) {

  }

  ngAfterViewInit() {
      console.log('messageContainer' , document.getElementById('message-container'));
     Smooch.render(document.getElementById('message-container'));
  }

  back(): void {
      this.nav.pop();
  }
}
```

If you would like, I could do a write up of the solution on a more simple example app.
![simulator screen shot nov 3 2016 6 45 40 pm](https://cloud.githubusercontent.com/assets/7246257/19991796/c117e0a8-a1f5-11e6-8453-54db74a58d74.png)

**Comment by sportebois** [comment]
Thanks a lot for your feedback! Great to hear it works in Ionic2. And even if it's what I had in mind with my first answer, it's always nice to get a confirmation it works. 

Please note that I edited your answer to remove the real token (I put a random one), but your token was there for a few hours though.

**Comment by lemieux** [comment]
Hey @thielCole if you don't mind doing a write up about this, it would be really nice! It could really help others in the same situation as you are.

**Comment by thielCole** [comment]
@sportebois Oh dam thanks... 

@lemieux Yeah, hopefully I can get around to this in the next week. I'll write a medium post on it or something.

**Comment by thielCole** [comment]
@lemieux I wanted to add to this a little bit. It seems that smooch.js overwrites the standard promise library implementation, because when I get an unhandled promise rejection error inside of my app, the error seems to log from smooch.min.js and not from the console. I would imagine this is a issue with the js implementation itself.

**Comment by thielCole** [comment]
@lemieux @sportebois I did that write-up about integrating smooch into our Ionic 2 application.

https://thielcole.github.io/ionic2/2016/11/15/smoochjs-ionic2-integration.html

Check it out and tell me what you think! I didn't make a repo that has it all pre-built, but I think the build isn't hard, just the two or three gotcha's in the initialization and configuration.

**Comment by sportebois** [comment]
Thanks a lot for kindly sharing your findings. 
Hopefully this will help other Ionic2 people looking into Smooch.

**Comment by jpsorensen** [comment]
Typescript definitions are now available for Smooch via DefinitelyTyped: https://www.npmjs.com/package/@types/smooch
