### ISSUE TITLE
Partnership ?

### ISSUE THREAD

**Issue by jcampbell05** [smooch/smooch-js#419]
I wasn't sure who to talk to but I've been working on a Bot Framework which has got some traction. I wanted to see if you wanted to partner up on building a component for it which allowed people to build a Bot which could be powered by smooch ? 

Here is the Github link
https://github.com/Bottr-js/Bottr

**Comment by mspensieri** [comment]
Hey @jcampbell05, thanks for your interest! You can visit our [partners page](https://smooch.io/partners/) for more information, and to submit an application to become a partner :)

**Comment by jcampbell05** [comment]
@mspensieri  Thank you :) ! I've submitted my application.
