### ISSUE TITLE
svg filter broken by <base href>

### ISSUE THREAD

**Issue by LeResKP** [smooch/smooch-js#422]
When adding a <base href> in a HTML page the url(#dropShadow) in the filter svg attribute is broken.

I created this plunker to reproduct the issue: http://plnkr.co/edit/93ezuVuxnqq7Q6GKfKzR?p=preview
(You need to provide an app_token)

Aurélien

**Comment by lemieux** [comment]
Hey @LeResKP,

thanks a lot for this report, you provided the missing data for a bug that we were trying to fix for a long time!

A fix is already in progress and should be released today.

Thanks again!

**Comment by lemieux** [comment]
Version 3.6.0 was just released and should contain the fix for this. Thanks again for the report!

**Comment by LeResKP** [comment]
@lemieux thks for your reactivity !
