### ISSUE TITLE
'document.hasFocus' is not a function on Opera Mini

### ISSUE THREAD

**Issue by klette** [smooch/smooch-js#425]
The following line seems to break Opera Mini somewhat.

https://github.com/smooch/smooch-js/blob/bd1b5d2aa6b3db833bf75717c726d2eb166242cf/src/js/utils/dom.js#L85

According to https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus it is known to no be supported on Opera Mini. 

Its a minor annoyance since the market share of that browser isn't that big, but would be nice with a small if-test to remove that error.

The error was reported from Opera Mini 4.5.40380

**Comment by lemieux** [comment]
Hey @klette, I'll make sure to sneak a fix for this in the next release. As you said, since Opera Mini doesn't have that much of a market share, we don't run test for it, but if we can make it better, we'll do it!

Thanks for the report!
