### ISSUE TITLE
Smooch tries to update a non existing user when calling Smooch.login

### ISSUE THREAD

**Issue by abrel** [smooch/smooch-js#445]
I guess it is related to #396 (which is an issue I get  as well). Smooch is also trying to do an update on a non existing user when I call Smooch.login.

Below is my code:

```
Smooch.login(user.id, {
            email: user.email,
            givenName: user.firstName,
            surname: user.lastName,
            signedUpAt: new Date(user.createdAt),
            properties: user,
          })
          .then(() => {
            console.log('--------------------------------');
            console.log('Smooch user id:', Smooch.getUserId());
            console.log('--------------------------------');
          })
          .catch(e => Promise.reject(e));
```

And this is what I get in the console:

PUT https://api.smooch.io/v1/appusers/1f4f12d4d8XXXXXd8af0e6315 404 (Not Found)
http.js?2cc4:45 Uncaught (in promise) Error: Not Found
    at handleStatus (eval at <anonymous> (bundle.js:5300), <anonymous>:45:17)
handleStatus @ http.js?2cc4:45
?d41d:90 --------------------------------
?d41d:91 Smooche user id: 584ada25073XXXXX6c4cc0bea
?d41d:92 --------------------------------

Eventually when calling Smooch.logout(), it does another put request with an undefine parameter in the url

PUT https://api.smooch.io/v1/appusers/undefined/devices/f4366049XXXXX43b0b8c39e8b0f6f283d 404 (Not Found)
http.js?2cc4:45 Uncaught (in promise) Error: Not Found
    at handleStatus (eval at <anonymous> (bundle.js:5300), <anon

**Comment by mspensieri** [comment]
An attempt was made to fix this in [v3.10.0](https://github.com/smooch/smooch-js/releases/tag/3.10.0). Please re-open if you can still reproduce with the latest version
