### ISSUE TITLE
js error after destroy() and init() with and without userId

### ISSUE THREAD

**Issue by pandaiolo** [smooch/smooch-js#489]
Use case : 

 - frequent `destroy()` and `init()` to show/hide Smooch on some routes of a single page app
 - user is logged in in my app, Smooch behaves correctly
 - user logs out from my app, while on its profile, where Smooch is not present
 - Logged out user is back on the home page, where Smooch is present, and `init()` again, this time without `userId` prop.

Then it starts to go wrong :
  1. Opening the chat **shows previous (private) conversations** from logged in user, despite Smooch is now inited **without** `userId`
  2. Sending a first message works (in slack, I see the message as anonymous), the older authenticated messages disappear from the chat, and the following error spawns in the console :

```
warning.js:36 Warning: Failed prop type: The prop `hasMoreMessages` is marked as required in `ConversationComponent`, but its value is `undefined`.
    in ConversationComponent (created by Connect(ConversationComponent))
    in Connect(ConversationComponent) (created by WidgetComponent)
    in div (created by WidgetComponent)
    in div (created by WidgetComponent)
    in div (created by WidgetComponent)
    in WidgetComponent (created by Connect(WidgetComponent))
    in Connect(WidgetComponent) (created by Root)
    in Provider (created by Root)
    in Root
```

*Note: probably not relevant but anyhow, my app is also a react app, testing in NODE_ENV=development, I guess the error about propTypes will disapear in production, but it's still an indication of a potential bug*

**Question**

 How should I do instead ? If users logs out without Smooch inited, should I `init()` *with* the `userId`, then logout Smooch, then call `destroy()` and only then logout user from my app ?

**Comment by lemieux** [comment]
Hey @pandaiolo, I'll check this out. We already know there's some problem with how we handle `destroy`. Is it possible that you call `destroy` when it's already destroyed?

Also, once Smooch is `init`ed and you want to swap users, you can call `.login()` instead.

Unless you want to hide the Web Messenger, you can do this 

- `Smooch.init()` at the beginning (with or without userId depending if in authenticated part or not of your app)
- `Smooch.logout()` when moving from authenticated to anonymous (it's an alias for `Smooch.login()` without userId if it's easier for you)
- `Smooch.login(userId)` when moving from anonymous to authenticated.

Note that if you have a conversation going while being anonymous and then you log in, your anonymous conversation will be merged in your authenticated conversation. But if you go back to anonymous, a new conversation will be started.

If you really need to make the Web Messenger disappears, that's probably where it get messy. We need to look into the `destroy` problem.

**Comment by pandaiolo** [comment]
Yes, because in a UI point of view, on a mobile device, every inch counts :) So we want to limit the appearance of Smooch on homepage and a few pages where asking help could be actually usefull.

I don't think I call `destroy()` when the element is already destroyed. Is there a way to know if `init()` has been called, or already succeed, and no previous `destroy()` has been called ? 

That being said, supporting indempotent operations is always a good development practice ;-)

Thank you, and let me know if you need more information

**Comment by lemieux** [comment]
Yeah `destroy` isn't supposed to have side effects like that. We'll fix it.
