### ISSUE TITLE
Proactive chat

### ISSUE THREAD

**Issue by fsalomon** [smooch/smooch-js#494]
Situation:
With a _new_ userId, I'm doing a
```
Smooch.init({
  appToken: '...',
  embedded: true,
  userId: '...',
  jwt: '...',
})
```

Then, I'm doing a 
`curl https://api.smooch.io/v1/appusers/.../messages -X POST -d '{"text":"Test message", "role": "appMaker", "type": "text"}' -H 'content-type: application/json' -H 'authorization: Bearer ...'`

Excepted result:
Operator's message would show in user's UI.

Actual result:
No message is delivered until the user sends a message.

Is this intended behaviour? Because if yes, it would prevent something the entire live chat industry seems to boast as a killer feature often called "proactive chat".

**Comment by mspensieri** [comment]
This behaviour is indeed intended - the SDK does not actively monitor for new messages unless

a) the call to `init` signals that a conversation has already been started for that user
b) the user has sent their first message
c) a Whisper is received

Whispers are the recommended way to do "proactive chat" in Smooch. You can configure a Whisper in the Smooch web app, and [trigger it](https://github.com/smooch/smooch-js#trackeventname) using a custom event - `Smooch.track('my-event')`. [More Info](https://docs.smooch.io/guide/automated-messages/)

If Whispers don't work for your use case for whatever reason, there is still the option to reach out  proactively using the API, but you will need to provide some signal to the SDK to indicate that a message has been sent and the conversation has been started. You can do this using the [`getConversation`](https://github.com/smooch/smooch-js#getconversation) method, which forces the SDK to request messages from the server.

```
Smooch.init({
   /* ... */
})
.then(function(){
  // Call your server to send the message
  /* ... */

  // Ask the SDK to fetch messages
  return Smooch.getConversation();
});
```

Hope that help!

**Comment by fsalomon** [comment]
Thanks for the insight!

I don't think whispers are going to work for me because I can't customize the text/icon/sender on a per-customer basis. But I have another websocket that I could use for signaling. Feels a bit hacky though :-(

Does a conversation that contains only the initial whisper count as a conversation in terms of billing?

**Comment by mspensieri** [comment]
Yes, a conversation with only a whisper in it is still considered a conversation
