### ISSUE TITLE
Smooch-js without dependency with react

### ISSUE THREAD

**Issue by edwinnnss** [smooch/smooch-js#497]
Can I use smooch-js without dependency with react ? because it always giving error on the console and using vue on my project
![image](https://cloud.githubusercontent.com/assets/13062493/23245538/d76b50ac-f9bf-11e6-900c-6529e73424f9.png)

**Comment by alavers** [comment]
Unfortunately smooch-js does depend on React, and the react runtime has shown to be incompatible with some web frameworks. One workaround would be to isolate smooch-js inside an iframe, which we realize isn't a simple workaround. We have an open issue to build support for iframe isolation as a built-in option in the near future.

**Comment by jaubut** [comment]
So we cant use smooch inside vue project ?

**Comment by alavers** [comment]
Good timing. We've actually just shipped a release that runs Smooch inside its own iframe, thus solving this incompatibility:

https://github.com/smooch/smooch-web/releases/tag/4.0.0

**Comment by edwinnnss** [comment]
GREAT!!
