### ISSUE TITLE
Wrong URL with HTML5 History API via pushState (ex: Angular $locationProvider.html5Mode(true))

### ISSUE THREAD

**Issue by DFOXpro** [smooch/smooch-js#500]
If a web using Smooch and a client site routing like Angular route, every message will only send the root page like it was the current page instead of the real route the client is looking.

## How to replicate
1. Setup an Angular basic page with some ngRoutes (EX: /test) and $locationProvider.html5Mode(true)
2. Setup Smooch
3. Start a chat within Smooch in some route

## Expected
Device info, Web messenger
```<domain> on <browser> ... looking at <domain>/<clientRoute>```

## WYG

Device info, Web messenger
```<domain> on <browser> ... looking at <domain>/```

How can I fix this error, can I use some of the event call to change this parameters?
or is this indeed a bug?

**Comment by lemieux** [comment]
Hmmm I'm not sure how Angular handles route changes but it seems it's doing so magic that doesn't end up calling `window.history.pushState` and we're listen to that to update the device info.

I'll add that to our internal bug tracker to see if we can find a workaround for it.

**Comment by DFOXpro** [comment]
I make a workaround and was to update smooch user properties in routeChange event.

**Comment by lemieux** [comment]
I'll close this since there's not much we can do about it as this is specific to Angular and a workaround was found for users.
