### ISSUE TITLE
Docs for Smooch.render()

### ISSUE THREAD

**Issue by chmac** [smooch/smooch-js#514]
Reading the docs I can't find any mention of how `Smooch.render()` should be called. From reading the code I guess it wants to be given an actual DOM element that gets passed to react-dom's `render()`. Would be great to have it listed in the functions API part of the README.

**Comment by lemieux** [comment]
Hey @chmac,

we talk about it a bit here https://github.com/smooch/smooch-js#embedded-mode but I agree it could be clearer. `Smooch.render` should only be used if you are using it in embedded mode.

I'll pass this to the team so we can make an improvement on the documentation.

**Comment by chmac** [comment]
Yeah, I got that. Just wasn't sure if it wanted a jQuery style selector (string `#someId`) or an actual DOM element. We work with React, so it was easy enough to figure out from the source, but my first step was to search the page for `.render()`, then `render()`, then `render` which didn't answer the question. :-)

**Comment by lemieux** [comment]
No problem :) We'll add it the the list.. clearly it's missing!
