### ISSUE TITLE
Initializing Smooch makes some icons disappear

### ISSUE THREAD

**Issue by nesk** [smooch/smooch-js#521]
This bug is absolutely insane. Whenever I initialize the Smooch client, some specific Font Awesome icons disappear…

I've created [an example on JS Bin](http://jsbin.com/qohuhawake/edit?html,css,js,output) so you can try by yourself. See the ["question mark" icon](http://fontawesome.io/icon/question-circle-o/)? Now specify a valid app token and it will disappear.

_[Here is a gist](https://gist.github.com/nesk/7fb1b39c20ffa45acfb77ae752d5a450) in case the JS Bin example becomes unavailable._

Here is what I know:

* This is specific to [this icon](http://fontawesome.io/icon/question-circle-o/), I didn't manage to find another icon disappearing.
* The icon visually disappears but is not removed from the DOM.
* It happens only when the Smooch client is initialized, never when the script is loaded.
* It doesn't seem to be a rendering issue of any specific browser since it happens across multiple browsers and engines.

Still, thank you for this awesome project. 🙂

**Comment by nesk** [comment]
And, generally, the icons are flickering on Smooch's initialization.

**Comment by nesk** [comment]
Ok, I've found what's wrong: you're loading your own version of Font Awesome.

Did you ever consider loading Smooch in an iframe? Stripe is doing that with their [Checkout script](https://stripe.com/docs/checkout) and it works well.

**Comment by lemieux** [comment]
Hey @nesk,

You are right, it is because we are loading our own version of Font Awesome. I made a fix in #522, should be release today.

**Comment by lemieux** [comment]
Fix is out with 3.14.2.

**Comment by nesk** [comment]
Thank you!
