### ISSUE TITLE
Smooch.sendMessage no longer gets a reply

### ISSUE THREAD

**Issue by mrazzari** [smooch/smooch-js#527]
I'm using an embedded widget, and using `Smooch.sendMessage()` when the widget is ready.
The message is sent, but I don't get a reply. 
Here's a minimal test-case: https://jsfiddle.net/49jwet9r/5/

After `sendMessage("Welcome")` a "Pleased to meet you" whisper should be received. 
The whisper is there if I look at [the logs](https://i.imgur.com/U4gEVCH.png) but nothing comes back on the front-end. If you simply re-run the fiddle you'll see both messages there, as expected.

Since I know this was working for me before, I built smooch.js **v3.13.3** from source, and the problem is not there. 
See the same demo using that older version: https://jsfiddle.net/49jwet9r/8/

![Expected behavior.](https://i.imgur.com/ovvLaKF.png)

**Comment by lemieux** [comment]
Hey @mrazzari, after my unsuccessful attempt at creating a fix in #528, I talked with the team and they come up with a simpler solution. Since calling `getConversation` will kick off the throttling, we suggest that you change a bit the way you check for an existing solution.

You could do this instead : 

```
var ready = Smooch.init({ 
    appToken: '5bspwx0wbivdtv7wy1hc7v82c', 
    embedded: true,
    imageUploadEnabled: false
});
Smooch.render(document.getElementById('chat-container'));	
ready.then(function(user) {
    if(!user.conversationStarted) {
        Smooch.sendMessage('Welcome!');
    }
});
```

and it should do the trick.

**Comment by mrazzari** [comment]
OK, this is useful, and it worked! 
Would be nice to document this param for the ready event in the readme. 

I'm also using getConversation as a hack to trigger a refresh (see #506) but this doesn't seem impacted by the changes in 3.14.

The fix works for my specific use case, so I'm happy to close the ticket. But I think you have a situation where 2 documented API methods are having an unexpected and obscure interaction. So it may be worth to keep looking into it.

**Comment by lemieux** [comment]
We'll look into it. Thanks!
