### ISSUE TITLE
Smooch crashes ChromeDriver

### ISSUE THREAD

**Issue by nesk** [smooch/smooch-js#532]
I encountered a curious issue while using [ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/). Whenever I load a page (which initializes Smooch) through the web driver, Chrome crashes.

It may not be your fault, but I thought you should be aware of this issue. I created a showcase in a clean repository so you can try by yourselves : [nesk/smooch-crash-chrome-web-driver](https://github.com/nesk/smooch-crash-chrome-web-driver)

FYI, I ran this repository under macOS v10.12.4. The issue may not occur on another OS/version.

**Comment by lemieux** [comment]
Hey @nesk,

I just tried your repo on Ubuntu 17.04 and it's working alright. Not sure how to help you on that, but I'll close this issue since it doesn't seem to be related to the Web Messenger.
