### ISSUE TITLE
How to track Stripe payment events?

### ISSUE THREAD

**Issue by ronak90** [smooch/smooch-js#533]
Hi,

We already have `Smooch.on('message:sent', function(message) { //TODO })` and `Smooch.on('message:received', function(message) { //TODO })` for tracking messages that are sent and received respectively which get fired whenever message is sent or received. 

I am using [Motion.AI](https://www.motion.ai) for bot and I have integrated Smooch it it. I am sending payment button using API of Motion.AI with Smooch special snippet that's `You will be charged for $10 $[Pay Now]($10)`, it gives payment button to user. Clicking on it opens popup to enter credit card info and email. If payment is done successfully then the button text is changed but there is no event which gets fired which notifies me if payment was done successfully or not. I need to call further API based on success of payment. I tried `Smooch.on('payment:success', function(message) { //TODO })`  but probably it's not firing when payment is completed successfully.

So how can I track payment related events?

Thanks!

**Comment by lemieux** [comment]
Hi @ronak90,

there's currently no way to do it client-side. However, you can receive notifications of successful payments by subscribing to webhooks in the backend (https://docs.smooch.io/rest/#webhooks).

I hope this help!
