### ISSUE TITLE
PropTypes and CreateClass Deprecation Warnings

### ISSUE THREAD

**Issue by koofka** [smooch/smooch-js#556]
As of 3.15.0 the package is pitching deprecation warning for accessing PropTypes via the main React package and is also pitching a createClass deprecation warning on the version of react-stripe-checkout implemented.  

Appears that the latter package resolves the createClass deprecation as of the current version 2.4 versus the installed 1.7.2. 

The PropTypes issue should be straightforward to correct via implementation of the prop-types package and replacement of the imports of `{PropTypes} from 'react'` are removed and `import PropTypes from 'prop-types'` is added.

**Comment by lemieux** [comment]
Hey @koofka,

I'm actually working on a new feature and as part of it, we upgraded a lot of dependencies (including React). It should go out somewhere towards the end of summer and it should fix this issue. 

Since those are just warnings and a fix is coming, I'll close this this.

**Comment by cgcote** [comment]
Hey @lemieux, is _end of summer_ still the plan? React.createClass is no longer supported by React 16 which should be released in the coming days.

Thanks!

**Comment by lemieux** [comment]
Yup, should definitely be out before Sept 21 ;)

**Comment by lemieux** [comment]
Hey @cgcote, version 4.0.0 is out with the fixes. Make sure to read the release notes https://github.com/smooch/smooch-web/releases/tag/4.0.0 and the updated README https://github.com/smooch/smooch-web/blob/integration/README.md if you want to upgrade.
