### ISSUE TITLE
Refused to connect to wss://api.amooch.io/faye' because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy

### ISSUE THREAD

**Issue by kenyeung128** [smooch/smooch-js#579]
Refused to connect to wss://api.amooch.io/faye' because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy

Does anyone has this issue? some browsers in iphone throw this error, and can't get the message from the server.

**Comment by lemieux** [comment]
Hey @kenyeung128, can you give me more info about the OS used? I found an issue here https://github.com/meteor/meteor/issues/7772 that looks related about websockets on IOS 10.

**Comment by kenyeung128** [comment]
It's IOS v10.3, how we shall resolve this?

On 1 Aug 2017 11:14 PM, "Marc-Antoine Lemieux" <notifications@github.com>
wrote:

Hey @kenyeung128 <https://github.com/kenyeung128>, can you give me more
info about the OS used? I found an issue here meteor/meteor#7772
<https://github.com/meteor/meteor/issues/7772> that looks related about
websockets on IOS 10.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/smooch/smooch-js/issues/579#issuecomment-319394888>,
or mute
the thread

**Comment by lemieux** [comment]
Also, in which browser is this happening?

**Comment by lemieux** [comment]
Ehh, just to be sure, is this the actual error message you are getting? I see `wss://api.amooch.io/faye` instead of `wss://api.smooch.io/faye`.. I'm guessing this is just a typo

**Comment by kenyeung128** [comment]
Yes actual error is wss://api.smooch.io/faye and I am using safari

**Comment by lemieux** [comment]
Do you have a test page I could try? I just try the widget on https://smooch.io and it worked fine on IOS 10 with Safari. I'm trying to figure out why it's not working for you.

**Comment by lemieux** [comment]
This should be fixed by #604 and released as 3.15.1
